// <auto-generated />
using CatalogService.Api.Repostories.StockReps;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogService.Api.Migrations
{
    [DbContext(typeof(StockContext))]
    [Migration("20240121121113_StockCatalogAdded")]
    partial class StockCatalogAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Api.Models.Domain.Stock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = "83e3a375-ad4a-4335-ae1b-3f641fc55b80",
                            Company = "Example Company",
                            Name = "EXMP",
                            Price = 59.120m
                        },
                        new
                        {
                            Id = "8ec2ecdd-9250-4ded-b11e-9b1bc796b194",
                            Company = "Example the second Company",
                            Name = "EXMP2",
                            Price = 299.10m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
